In [1]:
%load_ext sql

In [2]:
%sql postgresql://student:student@127.0.0.1/sparkifydb

'Connected: student@sparkifydb'

In [8]:
%sql SELECT * FROM songplays LIMIT 50;

 * postgresql://student:***@127.0.0.1/sparkifydb
50 rows affected.

[(1, 1543537327796, 91, 'free', None, None, 829, 'Dallas-Fort Worth-Arlington, TX', 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)'),
 (2, 1543540121796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (3, 1543540368796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (4, 1543540625796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (5, 1543540856796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (6, 1543541072796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (7, 1543541299796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (8, 1543541520796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (9, 1543541897796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (10, 1543541993796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (11, 1543542250796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (12, 1543542516796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (13, 1543542628796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (14, 1543542935796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (15, 1543543268796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (16, 1543543524796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (17, 1543543821796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (18, 1543544154796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (19, 1543544359796, 73, 'paid', None, None, 1049, 'Tampa-St. Petersburg-Clearwater, FL', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"'),
 (20, 1543547190796, 86, 'free', None, None, 986, 'La Crosse-Onalaska, WI-MN', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36"'),
 (21, 1543547430796, 86, 'free', None, None, 986, 'La Crosse-Onalaska, WI-MN', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36"'),
 (22, 1543547583796, 86, 'free', None, None, 986, 'La Crosse-Onalaska, WI-MN', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36"'),
 (23, 1543547741796, 86, 'free', None, None, 986, 'La Crosse-Onalaska, WI-MN', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36"'),
 (24, 1543548069796, 86, 'free', None, None, 986, 'La Crosse-Onalaska, WI-MN', '"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36"'),
 (25, 1543548563796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (26, 1543548766796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (27, 1543549044796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (28, 1543549171796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (29, 1543549468796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (30, 1543549790796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (31, 1543550142796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (32, 1543550301796, 26, 'free', None, None, 1068, 'San Jose-Sunnyvale-Santa Clara, CA', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"'),
 (33, 1543550457796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (34, 1543550653796, 26, 'free', None, None, 1068, 'San Jose-Sunnyvale-Santa Clara, CA', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"'),
 (35, 1543550761796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (36, 1543550960796, 26, 'free', None, None, 1068, 'San Jose-Sunnyvale-Santa Clara, CA', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"'),
 (37, 1543551178796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (38, 1543551187796, 26, 'free', None, None, 1068, 'San Jose-Sunnyvale-Santa Clara, CA', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"'),
 (39, 1543551430796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (40, 1543551632796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (41, 1543551680796, 26, 'free', None, None, 1068, 'San Jose-Sunnyvale-Santa Clara, CA', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"'),
 (42, 1543551811796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (43, 1543551890796, 26, 'free', None, None, 1068, 'San Jose-Sunnyvale-Santa Clara, CA', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"'),
 (44, 1543552009796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (45, 1543552034796, 26, 'free', None, None, 1068, 'San Jose-Sunnyvale-Santa Clara, CA', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"'),
 (46, 1543552268796, 24, 'paid', None, None, 1051, 'Lake Havasu City-Kingman, AZ', '"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"'),
 (47, 1543552322796, 26, 'free', None, None, 1068, 'San Jose-Sunnyvale-Santa Clara, CA', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"'),
 (48, 1543552590796, 26, 'free', None, None, 1068, 'San Jose-Sunnyvale-Santa Clara, CA', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"'),
 (49, 1543552925796, 49, 'paid', None, None, 1079, 'San Francisco-Oakland-Hayward, CA', 'Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0'),
 (50, 1543553163796, 49, 'paid', None, None, 1079, 'San Francisco-Oakland-Hayward, CA', 'Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0')]

In [4]:
%sql SELECT * FROM users LIMIT 50;

 * postgresql://student:***@127.0.0.1/sparkifydb
50 rows affected.

[(91, 'Jayden', 'Bell', 'M', 'free'),
 (73, 'Jacob', 'Klein', 'M', 'paid'),
 (86, 'Aiden', 'Hess', 'M', 'free'),
 (24, 'Layla', 'Griffin', 'F', 'paid'),
 (26, 'Ryan', 'Smith', 'M', 'free'),
 (49, 'Chloe', 'Cuevas', 'F', 'paid'),
 (57, 'Katherine', 'Gay', 'F', 'free'),
 (30, 'Avery', 'Watkins', 'F', 'paid'),
 (92, 'Ryann', 'Smith', 'F', 'free'),
 (74, 'Braden', 'Parker', 'M', 'free'),
 (88, 'Mohammad', 'Rodriguez', 'M', 'paid'),
 (36, 'Matthew', 'Jones', 'M', 'paid'),
 (12, 'Austin', 'Rosales', 'M', 'free'),
 (61, 'Samuel', 'Gonzalez', 'M', 'free'),
 (43, 'Jahiem', 'Miles', 'M', 'free'),
 (85, 'Kinsley', 'Young', 'F', 'paid'),
 (50, 'Ava', 'Robinson', 'F', 'free'),
 (101, 'Jayden', 'Fox', 'M', 'free'),
 (16, 'Rylan', 'George', 'M', 'paid'),
 (78, 'Chloe', 'Roth', 'F', 'free'),
 (33, 'Bronson', 'Harris', 'M', 'free'),
 (5, 'Elijah', 'Davis', 'M', 'free'),
 (69, 'Anabelle', 'Simpson', 'F', 'free'),
 (32, 'Lily', 'Burns', 'F', 'free'),
 (75, 'Joseph', 'Gutierrez', 'M', 'free'),
 (96, 'Cierra', 'Finley', 'F', 'free'),
 (44, 'Aleena', 'Kirby', 'F', 'paid'),
 (67, 'Colm', 'Santana', 'M', 'free'),
 (62, 'Connar', 'Moreno', 'M', 'free'),
 (14, 'Theodore', 'Harris', 'M', 'free'),
 (80, 'Tegan', 'Levine', 'F', 'paid'),
 (35, 'Molly', 'Taylor', 'F', 'free'),
 (66, 'Kevin', 'Arellano', 'M', 'free'),
 (63, 'Ayla', 'Johnson', 'F', 'free'),
 (58, 'Emily', 'Benson', 'F', 'paid'),
 (6, 'Cecilia', 'Owens', 'F', 'free'),
 (53, 'Celeste', 'Williams', 'F', 'free'),
 (56, 'Cienna', 'Freeman', 'F', 'free'),
 (94, 'Noah', 'Chavez', 'M', 'free'),
 (98, 'Jordyn', 'Powell', 'F', 'free'),
 (90, 'Andrea', 'Butler', 'F', 'free'),
 (40, 'Tucker', 'Garrison', 'M', 'free'),
 (60, 'Devin', 'Larson', 'M', 'free'),
 (10, 'Sylvie', 'Cruz', 'F', 'free'),
 (17, 'Makinley', 'Jones', 'F', 'free'),
 (47, 'Kimber', 'Norris', 'F', 'free'),
 (87, 'Dustin', 'Lee', 'M', 'free'),
 (29, 'Jacqueline', 'Lynch', 'F', 'paid'),
 (68, 'Jordan', 'Rodriguez', 'F', 'free'),
 (23, 'Morris', 'Gilmore', 'M', 'free')]

In [5]:
%sql SELECT * FROM songs LIMIT 5;

 * postgresql://student:***@127.0.0.1/sparkifydb
5 rows affected.

[('SOMZWCG12A8C13C480', "I Didn't Mean To", 'ARD7TVE1187B99BFB1', 0, 218.93179),
 ('SOUDSGM12AC9618304', 'Insatiable (Instrumental Version)', 'ARNTLGG11E2835DDB9', 0, 266.39628),
 ('SOIAZJW12AB01853F1', 'Pink World', 'AR8ZCNI1187B9A069B', 1984, 269.81832),
 ('SOHKNRJ12A6701D1F8', 'Drop of Rain', 'AR10USD1187B99F3F1', 0, 189.57016),
 ('SOCIWDW12A8C13D406', 'Soul Deep', 'ARMJAGH1187FB546F3', 1969, 148.03546)]

In [6]:
%sql SELECT * FROM artists LIMIT 5;

 * postgresql://student:***@127.0.0.1/sparkifydb
5 rows affected.

[('ARD7TVE1187B99BFB1', 'Casual', 'California - LA', None, None),
 ('ARNTLGG11E2835DDB9', 'Clp', '', None, None),
 ('AR8ZCNI1187B9A069B', 'Planet P Project', '', None, None),
 ('AR10USD1187B99F3F1', 'Tweeterfriendly Music', 'Burlington, Ontario, Canada', None, None),
 ('ARMJAGH1187FB546F3', 'The Box Tops', 'Memphis, TN', 35.14968, -90.04892)]

In [7]:
%sql SELECT * FROM time LIMIT 25;

 * postgresql://student:***@127.0.0.1/sparkifydb
25 rows affected.

[(1543537327796, 0, 30, 48, 11, 2018, '4'),
 (1543540121796, 1, 30, 48, 11, 2018, '4'),
 (1543540368796, 1, 30, 48, 11, 2018, '4'),
 (1543540625796, 1, 30, 48, 11, 2018, '4'),
 (1543540856796, 1, 30, 48, 11, 2018, '4'),
 (1543541072796, 1, 30, 48, 11, 2018, '4'),
 (1543541299796, 1, 30, 48, 11, 2018, '4'),
 (1543541520796, 1, 30, 48, 11, 2018, '4'),
 (1543541897796, 1, 30, 48, 11, 2018, '4'),
 (1543541993796, 1, 30, 48, 11, 2018, '4'),
 (1543542250796, 1, 30, 48, 11, 2018, '4'),
 (1543542516796, 1, 30, 48, 11, 2018, '4'),
 (1543542628796, 1, 30, 48, 11, 2018, '4'),
 (1543542935796, 1, 30, 48, 11, 2018, '4'),
 (1543543268796, 2, 30, 48, 11, 2018, '4'),
 (1543543524796, 2, 30, 48, 11, 2018, '4'),
 (1543543821796, 2, 30, 48, 11, 2018, '4'),
 (1543544154796, 2, 30, 48, 11, 2018, '4'),
 (1543544359796, 2, 30, 48, 11, 2018, '4'),
 (1543547190796, 3, 30, 48, 11, 2018, '4'),
 (1543547430796, 3, 30, 48, 11, 2018, '4'),
 (1543547583796, 3, 30, 48, 11, 2018, '4'),
 (1543547741796, 3, 30, 48, 11, 2018, '4'),
 (1543548069796, 3, 30, 48, 11, 2018, '4'),
 (1543548563796, 3, 30, 48, 11, 2018, '4')]

## REMEMBER: Restart this notebook to close connection to `sparkifydb`
Each time you run the cells above, remember to restart this notebook to close the connection to your database. Otherwise, you won't be able to run your code in `create_tables.py`, `etl.py`, or `etl.ipynb` files since you can't make multiple connections to the same database (in this case, sparkifydb).

In [12]:
%sql SELECT * FROM songplays WHERE artist_id != 'None' AND song_id != 'None' LIMIT 50;

 * postgresql://student:***@127.0.0.1/sparkifydb
1 rows affected.

[(4108, 1542837407796, 15, 'paid', 'SOZCTXZ12AB0182364', 'AR5KOSW1187FB35FF4', 818, 'Chicago-Naperville-Elgin, IL-IN-WI', '"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"')]